[build]
builder = "python"
pythonVersion = "3.10"

[build.packages]
pkgs = ["python310"]

[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "cd Backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
